-- V1: Criacao das tabelas principais do sistema de investimentos
-- Este arquivo e um REQUISITO da professora - NAO REMOVER

-- Tabela de usuarios
CREATE TABLE IF NOT EXISTS TB_USUARIO (
    id_usuario NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    senha VARCHAR2(255) NOT NULL,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ativo NUMBER(1) DEFAULT 1 CHECK (ativo IN (0, 1))
);

-- Tabela de tipos de investimento
CREATE TABLE IF NOT EXISTS TB_TIPO_INVESTIMENTO (
    id_tipo NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(50) NOT NULL UNIQUE,
    descricao VARCHAR2(255),
    risco VARCHAR2(20) CHECK (risco IN ('BAIXO', 'MEDIO', 'ALTO')),
    rentabilidade_esperada NUMBER(5,2)
);

-- Tabela de investimentos
CREATE TABLE IF NOT EXISTS TB_INVESTIMENTO (
    id_investimento NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    descricao VARCHAR2(500),
    valor_minimo NUMBER(10,2) DEFAULT 0,
    rentabilidade NUMBER(5,2),
    prazo_meses NUMBER(3),
    id_tipo NUMBER(10) NOT NULL,
    ativo NUMBER(1) DEFAULT 1 CHECK (ativo IN (0, 1)),
    CONSTRAINT FK_INVESTIMENTO_TIPO FOREIGN KEY (id_tipo) REFERENCES TB_TIPO_INVESTIMENTO(id_tipo)
);

-- Tabela de relacionamento usuario-investimento
CREATE TABLE IF NOT EXISTS TB_USUARIO_INVESTIMENTO (
    id_usuario_investimento NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER(10) NOT NULL,
    id_investimento NUMBER(10) NOT NULL,
    valor_investido NUMBER(12,2) NOT NULL,
    data_investimento TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_vencimento DATE,
    status VARCHAR2(20) DEFAULT 'ATIVO' CHECK (status IN ('ATIVO', 'RESGATADO', 'VENCIDO')),
    CONSTRAINT FK_USUARIO_INV_USUARIO FOREIGN KEY (id_usuario) REFERENCES TB_USUARIO(id_usuario),
    CONSTRAINT FK_USUARIO_INV_INVESTIMENTO FOREIGN KEY (id_investimento) REFERENCES TB_INVESTIMENTO(id_investimento)
);

-- Indices para otimizacao
CREATE INDEX IF NOT EXISTS IDX_USUARIO_EMAIL ON TB_USUARIO(email);
CREATE INDEX IF NOT EXISTS IDX_INVESTIMENTO_TIPO ON TB_INVESTIMENTO(id_tipo);
CREATE INDEX IF NOT EXISTS IDX_USUARIO_INV_USUARIO ON TB_USUARIO_INVESTIMENTO(id_usuario);
CREATE INDEX IF NOT EXISTS IDX_USUARIO_INV_INVESTIMENTO ON TB_USUARIO_INVESTIMENTO(id_investimento);

-- Comentarios das tabelas
COMMENT ON TABLE TB_USUARIO IS 'Tabela de usuarios do sistema';
COMMENT ON TABLE TB_TIPO_INVESTIMENTO IS 'Tipos de investimento disponiveis';
COMMENT ON TABLE TB_INVESTIMENTO IS 'Investimentos oferecidos pela plataforma';
COMMENT ON TABLE TB_USUARIO_INVESTIMENTO IS 'Relacionamento entre usuarios e seus investimentos';